<?php

use App\Http\Controllers\Admin\AdminResearchController;
use App\Http\Controllers\Admin\AdminTestimoniController;
use App\Http\Controllers\Admin\Certificate;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\GalleryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\DosenController;
use App\Http\Controllers\AsistantController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Lead\LeadNewsController;
use App\Http\Controllers\Admin\TrainingController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\Admin\MahasiswaController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Lead\LeadTrainingController;
use App\Http\Controllers\Admin\NewsCategoryController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Lead\LeadMahasiswaController;
use App\Http\Controllers\Admin\ReleaseCategoryController;
use App\Http\Controllers\Admin\ReleaseController;
use App\Http\Controllers\Admin\TeacherController;
use App\Http\Controllers\Admin\ToolController;
use App\Http\Controllers\Asistant\AsistantNewsController;
use App\Http\Controllers\Lead\LeadNewsCategoryController;
use App\Http\Controllers\Admin\TrainingCategoryController;
use App\Http\Controllers\Asistant\AsistantContactController;
use App\Http\Controllers\Asistant\AsistantCustomerController;
use App\Http\Controllers\Asistant\AsistantGalleryController;
use App\Http\Controllers\Lead\LeadReleaseCategoryController;
use App\Http\Controllers\Asistant\AsistantTrainingController;
use App\Http\Controllers\Lead\LeadTrainingCategoryController;
use App\Http\Controllers\Asistant\AsistantMahasiswaController;
use App\Http\Controllers\Asistant\AsistantNewsCategoryController;
use App\Http\Controllers\Asistant\AsistantProfileController;
use App\Http\Controllers\Asistant\AsistantReleaseCategoryController;
use App\Http\Controllers\Asistant\AsistantReleaseController;
use App\Http\Controllers\Asistant\AsistantTeacherController;
use App\Http\Controllers\Asistant\AsistantToolController;
use App\Http\Controllers\Asistant\AsistantTrainingCategoryController;
use App\Http\Controllers\Dosen\CommunityDedicationController;
use App\Http\Controllers\Lead\LeadContactController;
use App\Http\Controllers\Lead\LeadCustomerController;
use App\Http\Controllers\Lead\LeadGalleryController;
use App\Http\Controllers\Lead\LeadProfileController;
use App\Http\Controllers\Lead\LeadReleaseController;
use App\Http\Controllers\Lead\LeadTeacherController;
use App\Http\Controllers\Admin\ScheduleController;
use App\Http\Controllers\Admin\SchedulePeriodeController;
use App\Http\Controllers\Dosen\DosenNewsController;
use App\Http\Controllers\Dosen\ResearchTeacherController;
use App\Http\Controllers\Lead\LeadResearchController;
use App\Http\Controllers\User\ResearchController;
use App\Http\Controllers\User\UserNewsController;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/whatsapp', [HomeController::class, 'whatsapp'])->name('whatsapp');
Route::get('/media-sosial', [HomeController::class, 'social'])->name('social');
Route::get('/tentang-kami', [HomeController::class, 'profile'])->name('home.profile');
Route::get('/struktur-organisasi', [HomeController::class, 'structure'])->name('home.structure');
Route::get('/galeri', [HomeController::class, 'galleries'])->name('home.galleries');
Route::get('/galeri-kegiatan/{id}', [HomeController::class, 'galleriesActivities'])->name('home.galleries.activities');
Route::get('/jadwal', [HomeController::class, 'schedules'])->name('home.schedules');
Route::get('/frequently-ask-question', [HomeController::class, 'faq'])->name('home.faq');
Route::get('/peralatan-laboratorium-praktikum', [HomeController::class, 'tools'])->name('home.tools');
Route::get('/peralatan-laboratorium-penelitian', [HomeController::class, 'toolsResearchs'])->name('home.tools.researchs');
Route::get('/testimoni', [HomeController::class, 'testimonies'])->name('home.testimonies');
Route::post('admin/testimoni/tambah', [AdminController::class, 'testimoniAdmin'])->name('admin.testimoni');
Route::post('asistant/testimoni/tambah', [AsistantController::class, 'testimoniAsistant'])->name('asistant.testimoni');
Route::post('dosen/testimoni/tambah', [DosenController::class, 'testimoniDosen'])->name('dosen.testimoni');
Route::post('lead/testimoni/tambah', [LeadController::class, 'testimoniLead'])->name('lead.testimoni');
Route::post('mahasiswa/testimoni/tambah', [DashboardController::class, 'testimoniUser'])->name('user.testimoni');
Route::get('/kategori-berita/{id}', [HomeController::class, 'categories'])->name('home.news.categories');
Route::get('/berita', [HomeController::class, 'news'])->name('home.news');
Route::get('/berita/detail/{id}', [HomeController::class, 'new'])->name('home.news.detail');
Route::get('/kategori-rilis/{id}', [HomeController::class, 'categoriesRelease'])->name('home.release.categories');
Route::get('/rilis', [HomeController::class, 'releases'])->name('home.release');
Route::get('/rilis/detail/{id}', [HomeController::class, 'release'])->name('home.release.detail');
Route::get('/kategori-pelatihan/{id}', [HomeController::class, 'categoriesTraining'])->name('home.training.categories');
Route::get('/pelatihan', [HomeController::class, 'trainings'])->name('home.trainings');
Route::get('/pelatihan/detail/{id}', [HomeController::class, 'training'])->name('home.training');
Route::get('/pengabdian-masyarakat', [HomeController::class, 'dedications'])->name('home.dedications');
Route::get('/pengabdian-masyarakat/detail/{id}', [HomeController::class, 'dedication'])->name('home.dedication');
Route::get('/penelitian', [HomeController::class, 'researchs'])->name('home.researchs');
Route::get('/penelitian/detail/{id}', [HomeController::class, 'research'])->name('home.research');
Route::get('/penelitian/hasil', [HomeController::class, 'researchResult'])->name('home.research.result');
Route::get('/kegiatan/dosen/{id}', [HomeController::class, 'teacher'])->name('home.dosen');
Route::get('/unduhan', [HomeController::class, 'download'])->name('download');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::post('/subscribe', [HomeController::class, 'subscribe'])->name('subscribe');
Route::post('/question', [DashboardController::class, 'question'])->name('question');
Route::post('/berita/komentar/{id}', [DashboardController::class, 'comment'])->name('mahasiswa.comment');
Route::post('/rilis/komentar/{id}', [DashboardController::class, 'commentRelease'])->name('mahasiswa.comment.release');
Route::get('/pengabdian-masyarakat/daftar/{id}', [DashboardController::class, 'dedicationEnroll'])->name('mahasiswa.daftar.pengabdian');
Route::get('/penelitian/daftar/{id}', [DashboardController::class, 'researchEnroll'])->name('mahasiswa.daftar.penelitian'); 
Route::get('/penelitian/tugas-akhir/daftar', [DashboardController::class, 'finalTaskEnroll'])->name('home.final.task'); 
Route::get('/penelitian/magang/daftar', [DashboardController::class, 'internshipEnroll'])->name('home.internship'); 
Route::get('/penelitian/individu/daftar', [DashboardController::class, 'researchIndividuEnroll'])->name('home.research.individu'); 
Route::get('/praktikum/daftar', [DashboardController::class, 'practice'])->name('home.practice'); 
Route::get('/surat-keterangan-bebas-laboratorium', [DashboardController::class, 'certificateClearenceLaboratory'])->name('home.laboratory.clearance.certificate'); 
Route::post('/penelitian/individu', [ResearchController::class, 'enroll'])->name('mahasiswa.daftar.penelitian.individu');
Route::post('/praktikum/daftar', [DashboardController::class, 'practiceEnroll'])->name('mahasiswa.daftar.praktikum');

Route::prefix('admin')->group(function(){
    Route::get('/profile/vission', [ProfileController::class, 'vission'])->middleware('admin')->name('admin.vission');
    Route::post('/profile/vission', [ProfileController::class, 'vissionUpdate'])->middleware('admin')->name('admin.vission.update');
    Route::get('/profile/mission', [ProfileController::class, 'mission'])->middleware('admin')->name('admin.mission');
    Route::post('/profile/mission', [ProfileController::class, 'missionUpdate'])->middleware('admin')->name('admin.mission.update');
    Route::get('/profile/goal', [ProfileController::class, 'goal'])->middleware('admin')->name('admin.goal');
    Route::post('/profile/goal', [ProfileController::class, 'goalUpdate'])->middleware('admin')->name('admin.goal.update');
    Route::get('/contact', [ContactController::class, 'index'])->middleware('admin')->name('admin.contact');
    Route::post('/contact', [ContactController::class, 'update'])->middleware('admin')->name('admin.contact.update');
    Route::get('/get-regency/ajax/{province_id}', [ContactController::class, 'GetRegency'])->middleware('admin');
    Route::get('/get-district/ajax/{regency_id}', [ContactController::class, 'GetDisctrict'])->middleware('admin');
    Route::get('/get-village/ajax/{district_id}', [ContactController::class, 'GetVillage'])->middleware('admin');
    Route::post('/berita/komentar/{id}', [AdminController::class, 'comment'])->middleware('admin')->name('admin.comment');
    Route::post('/rilis/komentar/{id}', [AdminController::class, 'commentRelease'])->middleware('admin')->name('admin.comment.release');
    Route::get('/profile/edit', [AdminController::class, 'profile'])->middleware('admin')->name('admin.profile');
    Route::post('/profile/update', [AdminController::class, 'profileEdit'])->middleware('admin')->name('admin.profile.submit');
    Route::get('/profile/edit-password', [AdminController::class, 'password'])->middleware('admin')->name('admin.password');
    Route::post('/profile/update-password', [AdminController::class, 'passwordEdit'])->middleware('admin')->name('admin.password.submit');
    Route::get('/profile/edit/image', [AdminController::class, 'image'])->middleware('admin')->name('admin.profile.image');
    Route::post('/profile/edit/image', [AdminController::class, 'imageSubmit'])->middleware('admin')->name('admin.profile.image.submit');
    Route::get('/news-category', [NewsCategoryController::class, 'index'])->name('admin.news-category')->middleware('admin');
    Route::get('/news-category/add', [NewsCategoryController::class, 'create'])->name('admin.news-category.add')->middleware('admin');
    Route::post('/news-category/store', [NewsCategoryController::class, 'store'])->name('admin.news-category.store')->middleware('admin');
    Route::get('/news-category/edit/{id}', [NewsCategoryController::class, 'edit'])->name('admin.news-category.edit')->middleware('admin');
    Route::post('/news-category/update/{id}', [NewsCategoryController::class, 'update'])->name('admin.news-category.update')->middleware('admin');
    Route::get('/news-category/delete/{id}', [NewsCategoryController::class, 'destroy'])->name('admin.news-category.delete')->middleware('admin');
    Route::get('/news', [NewsController::class, 'index'])->name('admin.news')->middleware('admin');
    Route::get('/news/add', [NewsController::class, 'create'])->name('admin.news.add')->middleware('admin');
    Route::post('/news/store', [NewsController::class, 'store'])->name('admin.news.store')->middleware('admin');
    Route::get('/news/edit/{id}', [NewsController::class, 'edit'])->name('admin.news.edit')->middleware('admin');
    Route::post('/news/update/{id}', [NewsController::class, 'update'])->name('admin.news.update')->middleware('admin');
    Route::get('/news/detail/{id}', [NewsController::class, 'show'])->name('admin.news.show')->middleware('admin');
    Route::get('/news/delete/{id}', [NewsController::class, 'destroy'])->name('admin.news.delete')->middleware('admin');
    Route::get('/news/request', [NewsController::class, 'request'])->name('admin.news.request')->middleware('admin');
    Route::post('/news/request/acc/', [NewsController::class, 'acc'])->name('admin.news.request.acc')->middleware('admin');
    Route::get('/training-category', [TrainingCategoryController::class, 'index'])->name('admin.training-category')->middleware('admin');
    Route::get('/training-category/add', [TrainingCategoryController::class, 'create'])->name('admin.training-category.add')->middleware('admin');
    Route::post('/training-category/store', [TrainingCategoryController::class, 'store'])->name('admin.training-category.store')->middleware('admin');
    Route::get('/training-category/edit/{id}', [TrainingCategoryController::class, 'edit'])->name('admin.training-category.edit')->middleware('admin');
    Route::post('/training-category/update/{id}', [TrainingCategoryController::class, 'update'])->name('admin.training-category.update')->middleware('admin');
    Route::get('/training-category/delete/{id}', [TrainingCategoryController::class, 'destroy'])->name('admin.training-category.delete')->middleware('admin');
    Route::get('/training', [TrainingController::class, 'index'])->name('admin.training')->middleware('admin');
    Route::get('/training/add', [TrainingController::class, 'create'])->name('admin.training.add')->middleware('admin');
    Route::post('/training/store', [TrainingController::class, 'store'])->name('admin.training.store')->middleware('admin');
    Route::get('/training/edit/{id}', [TrainingController::class, 'edit'])->name('admin.training.edit')->middleware('admin');
    Route::post('/training/update/image/{id}', [TrainingController::class, 'updateImage'])->name('admin.training.update.image')->middleware('admin');
    Route::post('/training/update/form/{id}', [TrainingController::class, 'updateForm'])->name('admin.training.update.form')->middleware('admin');
    Route::post('/training/update/image-trainer/{id}', [TrainingController::class, 'updateImageTrainer'])->name('admin.training.update.image.trainer')->middleware('admin');
    Route::post('/training/update/form-trainer/{id}', [TrainingController::class, 'updateFormTrainer'])->name('admin.training.update.form.trainer')->middleware('admin');
    Route::get('/training/detail/{id}', [TrainingController::class, 'show'])->name('admin.training.show')->middleware('admin');
    Route::get('/training/delete/{id}', [TrainingController::class, 'destroy'])->name('admin.training.delete')->middleware('admin');
    Route::get('/training/learning-material/{id}', [TrainingController::class, 'learningMaterial'])->name('admin.training.learning.material')->middleware('admin');    
    Route::post('/training/learning-material/{id}', [TrainingController::class, 'uploadLearningMaterial'])->name('admin.training.learning.material.upload')->middleware('admin');    
    Route::get('/training/participants/{id}', [TrainingController::class, 'participants'])->name('admin.training.participants')->middleware('admin');
    Route::get('/training/participants/export/{id}', [TrainingController::class, 'export'])->name('admin.training.participants.export')->middleware('admin');
    Route::get('/training/status/active', [TrainingController::class, 'active'])->name('admin.training.status.active')->middleware('admin');
    Route::get('/training/status/unactive', [TrainingController::class, 'unactive'])->name('admin.training.status.unactive')->middleware('admin');
    Route::get('penelitian', [AdminResearchController::class, 'index'])->name('admin.research')->middleware('admin');
    Route::get('penelitian/detail/{id}', [AdminResearchController::class, 'show'])->name('admin.research.detail')->middleware('admin');
    Route::post('penelitian/konfirmasi/{id}', [AdminResearchController::class, 'acc'])->name('admin.research.confirmation')->middleware('admin');
    Route::get('praktikum-mahasiswa', [AdminController::class, 'practice'])->name('admin.practice')->middleware('admin');
    Route::get('/release-category', [ReleaseCategoryController::class, 'index'])->name('admin.release-category')->middleware('admin');
    Route::get('/release-category/add', [ReleaseCategoryController::class, 'create'])->name('admin.release-category.add')->middleware('admin');
    Route::post('/release-category/store', [ReleaseCategoryController::class, 'store'])->name('admin.release-category.store')->middleware('admin');
    Route::get('/release-category/edit/{id}', [ReleaseCategoryController::class, 'edit'])->name('admin.release-category.edit')->middleware('admin');
    Route::post('/release-category/update/{id}', [ReleaseCategoryController::class, 'update'])->name('admin.release-category.update')->middleware('admin');
    Route::get('/release-category/delete/{id}', [ReleaseCategoryController::class, 'destroy'])->name('admin.release-category.delete')->middleware('admin');
    Route::get('/release', [ReleaseController::class, 'index'])->name('admin.release')->middleware('admin');
    Route::get('/release/add', [ReleaseController::class, 'create'])->name('admin.release.add')->middleware('admin');
    Route::post('/release/store', [ReleaseController::class, 'store'])->name('admin.release.store')->middleware('admin');
    Route::get('/release/edit/{id}', [ReleaseController::class, 'edit'])->name('admin.release.edit')->middleware('admin');
    Route::post('/release/update/{id}', [ReleaseController::class, 'update'])->name('admin.release.update')->middleware('admin');
    Route::get('/release/detail/{id}', [ReleaseController::class, 'show'])->name('admin.release.show')->middleware('admin');
    Route::get('/release/delete/{id}', [ReleaseController::class, 'destroy'])->name('admin.release.delete')->middleware('admin');
    Route::get('/mahasiswa', [MahasiswaController::class, 'index'])->name('admin.mahasiswa')->middleware('admin');
    Route::get('/mahasiswa/add', [MahasiswaController::class, 'create'])->name('admin.mahasiswa.add')->middleware('admin');
    Route::post('/mahasiswa/store', [MahasiswaController::class, 'store'])->name('admin.mahasiswa.store')->middleware('admin');
    Route::get('/mahasiswa/edit/{id}', [MahasiswaController::class, 'edit'])->name('admin.mahasiswa.edit')->middleware('admin');
    Route::post('/mahasiswa/update/{id}', [MahasiswaController::class, 'update'])->name('admin.mahasiswa.update')->middleware('admin');
    Route::get('/mahasiswa/delete/{id}', [MahasiswaController::class, 'destroy'])->name('admin.mahasiswa.delete')->middleware('admin');
    Route::get('/dosen', [TeacherController::class, 'index'])->name('admin.dosen')->middleware('admin');
    Route::get('/dosen/add', [TeacherController::class, 'create'])->name('admin.dosen.add')->middleware('admin');
    Route::post('/dosen/store', [TeacherController::class, 'store'])->name('admin.dosen.store')->middleware('admin');
    Route::get('/dosen/edit/{id}', [TeacherController::class, 'edit'])->name('admin.dosen.edit')->middleware('admin');
    Route::post('/dosen/update/{id}', [TeacherController::class, 'update'])->name('admin.dosen.update')->middleware('admin');
    Route::get('/dosen/delete/{id}', [TeacherController::class, 'destroy'])->name('admin.dosen.delete')->middleware('admin');
    Route::get('/message', [MessageController::class, 'index'])->name('admin.message')->middleware('admin');
    Route::get('/message/reply/{id}', [MessageController::class, 'reply'])->name('admin.message.reply')->middleware('admin');
    Route::post('/message/reply/submit/{id}', [MessageController::class, 'submit'])->name('admin.message.reply.submit')->middleware('admin');
    Route::get('/customer', [CustomerController::class, 'index'])->name('admin.customer')->middleware('admin');
    Route::get('/peralatan-lab', [ToolController::class, 'index'])->name('admin.tools')->middleware('admin');
    Route::get('/peralatan-lab/add', [ToolController::class, 'create'])->name('admin.tool.create')->middleware('admin');
    Route::post('/peralatan-lab/store', [ToolController::class, 'store'])->name('admin.tool.store')->middleware('admin');
    Route::get('/peralatan-lab/edit/{id}', [ToolController::class, 'edit'])->name('admin.tool.edit')->middleware('admin');
    Route::post('/peralatan-lab/update/{id}', [ToolController::class, 'update'])->name('admin.tool.update')->middleware('admin');
    Route::get('/peralatan-lab/delete/{id}', [ToolController::class, 'destroy'])->name('admin.tool.delete')->middleware('admin');
    Route::get('/peralatan-lab/export', [ToolController::class, 'export'])->name('admin.tool.export')->middleware('admin');
    Route::get('/galeri', [GalleryController::class, 'index'])->name('admin.galleries')->middleware('admin');
    Route::get('/galeri/add', [GalleryController::class, 'create'])->name('admin.gallery.add')->middleware('admin');
    Route::post('/galeri/store', [GalleryController::class, 'store'])->name('admin.gallery.store')->middleware('admin');
    Route::get('/galeri/edit/{id}', [GalleryController::class, 'edit'])->name('admin.gallery.edit')->middleware('admin');
    Route::post('/galeri/update/{id}', [GalleryController::class, 'update'])->name('admin.gallery.update')->middleware('admin');
    Route::get('/galeri/edit-image/{id}', [GalleryController::class, 'editImage'])->name('admin.gallery.edit.image')->middleware('admin');
    Route::post('/galeri/update-image/{id}', [GalleryController::class, 'updateImage'])->name('admin.gallery.update.image')->middleware('admin');
    Route::get('/galeri/delete-image/{id}', [GalleryController::class, 'deleteImage'])->name('admin.gallery.delete.image')->middleware('admin');
    Route::get('/galeri/delete/{id}', [GalleryController::class, 'destroy'])->name('admin.gallery.delete')->middleware('admin');
    Route::get('/jadwal', [ScheduleController::class, 'index'])->name('admin.schedules')->middleware('admin');
    Route::get('/jadwal/add', [ScheduleController::class, 'create'])->name('admin.schedule.add')->middleware('admin');
    Route::post('/jadwal/store', [ScheduleController::class, 'store'])->name('admin.schedule.store')->middleware('admin');
    Route::get('/jadwal/edit/{id}', [ScheduleController::class, 'edit'])->name('admin.schedule.edit')->middleware('admin');
    Route::post('/jadwal/update/{id}', [ScheduleController::class, 'update'])->name('admin.schedule.update')->middleware('admin');
    Route::get('/jadwal/delete/{id}', [ScheduleController::class, 'destroy'])->name('admin.schedule.delete')->middleware('admin');
    Route::get('/jadwal-semester', [SchedulePeriodeController::class, 'index'])->name('admin.schedule.period')->middleware('admin');
    Route::get('/jadwal-semester/add', [SchedulePeriodeController::class, 'create'])->name('admin.schedule.period.add')->middleware('admin');
    Route::post('/jadwal-semester/store', [SchedulePeriodeController::class, 'store'])->name('admin.schedule.period.store')->middleware('admin');
    Route::get('/jadwal-semester/edit/{id}', [SchedulePeriodeController::class, 'edit'])->name('admin.schedule.period.edit')->middleware('admin');
    Route::post('/jadwal-semester/update/{id}', [SchedulePeriodeController::class, 'update'])->name('admin.schedule.period.update')->middleware('admin');
    Route::get('/jadwal-semester/delete/{id}', [SchedulePeriodeController::class, 'destroy'])->name('admin.schedule.period.delete')->middleware('admin');
    Route::get('/faq', [FaqController::class, 'index'])->name('admin.faqs')->middleware('admin');
    Route::get('/faq/add', [FaqController::class, 'create'])->name('admin.faq.add')->middleware('admin');
    Route::post('/faq/store', [FaqController::class, 'store'])->name('admin.faq.store')->middleware('admin');
    Route::get('/faq/edit/{id}', [FaqController::class, 'edit'])->name('admin.faq.edit')->middleware('admin');
    Route::post('/faq/update/{id}', [FaqController::class, 'update'])->name('admin.faq.update')->middleware('admin');
    Route::get('/faq/delete/{id}', [FaqController::class, 'destroy'])->name('admin.faq.delete')->middleware('admin');
    Route::get('/testimoni', [AdminTestimoniController::class, 'index'])->name('admin.testimonies')->middleware('admin');
    Route::get('/testimoni/acc', [AdminTestimoniController::class, 'acc'])->name('admin.testimonies.acc')->middleware('admin');
    Route::get('/testimoni/unacc', [AdminTestimoniController::class, 'unacc'])->name('admin.testimonies.unacc')->middleware('admin');
    Route::get('/surat-keterangan-bebas-laboratorium', [Certificate::class, 'index'])->name('admin.laboratory.clearance.certificate')->middleware('admin');
    Route::get('/surat-keterangan-bebas-laboratorium-show/{id}', [Certificate::class, 'show'])->name('admin.laboratory.clearance.certificate.detail')->middleware('admin');
    Route::get('surat-keterangan-bebas-laboratorium/kpm/{id}', [Certificate::class, 'kpm'])->name('admin.laboratory.clearance.certificate.kpm')->middleware('admin'); 
    Route::get('surat-keterangan-bebas-laboratorium/laporan-kp/{id}', [Certificate::class, 'laporanKp'])->name('admin.laboratory.clearance.certificate.laporan.kp')->middleware('admin'); 
    Route::get('surat-keterangan-bebas-laboratorium/form-ujian-ta/{id}', [Certificate::class, 'formUjianTa'])->name('admin.laboratory.clearance.certificate.form.ujian.ta')->middleware('admin'); 
    Route::get('surat-keterangan-bebas-laboratorium/pengesahan-kp/{id}', [Certificate::class, 'pengesahanKp'])->name('admin.laboratory.clearance.certificate.pengesahan.kp')->middleware('admin'); 
    Route::get('surat-keterangan-bebas-laboratorium/tanda-terima-proposal/{id}', [Certificate::class, 'tandaTerimaProposal'])->name('admin.laboratory.clearance.certificate.tanda.terima.proposal')->middleware('admin'); 
    Route::get('surat-keterangan-bebas-laboratorium/form-pengajuan/{id}', [Certificate::class, 'formPengajuan'])->name('admin.laboratory.clearance.certificate.form.pengajuan')->middleware('admin'); 
    Route::get('/surat-keterangan-bebas-laboratorium/acc/{id}', [Certificate::class, 'acc'])->name('admin.laboratory.clearance.certificate.acc')->middleware('admin');
    Route::get('/surat-keterangan-bebas-laboratorium/un-acc/{id}', [Certificate::class, 'unacc'])->name('admin.laboratory.clearance.certificate.unacc')->middleware('admin');
    Route::get('/surat-keterangan-bebas-laboratorium/{id}', [Certificate::class, 'certificateVerifyNumber'])->name('admin.laboratory.clearance.certificate.verify.number');
    Route::get('/surat-keterangan-bebas-laboratorium-add-number/{id}', [Certificate::class, 'certificateAddNumber'])->name('admin.laboratory.clearance.certificate.add.number');
    Route::post('/surat-keterangan-bebas-laboratorium-submit-number/{id}', [Certificate::class, 'certificateSubmitNumber'])->name('admin.laboratory.clearance.certificate.submit.number');
    Route::get('/surat-keterangan-bebas-laboratorium-result/{id}', [Certificate::class, 'certificateResult'])->name('admin.laboratory.clearance.certificate.result');
    Route::get('/login', [AdminController::class, 'index'])->name('admin.login.form');
    Route::post('/login', [AdminController::class, 'login'])->name('admin.login');
    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard')->middleware('admin');
    Route::get('logout', [AdminController::class, 'logout'])->name('admin.logout')->middleware('admin');
});

Route::prefix('asistant')->group(function(){
    Route::get('/profile/vission', [AsistantProfileController::class, 'vission'])->middleware('asistant')->name('asistant.vission');
    Route::post('/profile/vission', [AsistantProfileController::class, 'vissionUpdate'])->middleware('asistant')->name('asistant.vission.update');
    Route::get('/profile/mission', [AsistantProfileController::class, 'mission'])->middleware('asistant')->name('asistant.mission');
    Route::post('/profile/mission', [AsistantProfileController::class, 'missionUpdate'])->middleware('asistant')->name('asistant.mission.update');
    Route::get('/profile/goal', [AsistantProfileController::class, 'goal'])->middleware('asistant')->name('asistant.goal');
    Route::post('/profile/goal', [AsistantProfileController::class, 'goalUpdate'])->middleware('asistant')->name('asistant.goal.update');
    Route::get('/contact', [AsistantContactController::class, 'index'])->middleware('asistant')->name('asistant.contact');
    Route::post('/contact', [AsistantContactController::class, 'update'])->middleware('asistant')->name('asistant.contact.update');
    Route::get('/get-regency/ajax/{province_id}', [AsistantContactController::class, 'GetRegency'])->middleware('asistant');
    Route::get('/get-district/ajax/{regency_id}', [AsistantContactController::class, 'GetDisctrict'])->middleware('asistant');
    Route::get('/get-village/ajax/{district_id}', [AsistantContactController::class, 'GetVillage'])->middleware('asistant');
    Route::post('/berita/komentar/{id}', [AsistantController::class, 'comment'])->middleware('asistant')->name('asistant.comment');
    Route::post('/rilis/komentar/{id}', [AsistantController::class, 'commentRelease'])->middleware('asistant')->name('asistant.comment.release');
    Route::get('/profile/edit', [AsistantController::class, 'profile'])->middleware('asistant')->name('asistant.profile');
    Route::post('/profile/update', [AsistantController::class, 'profileEdit'])->middleware('asistant')->name('asistant.profile.submit');
    Route::get('/profile/edit-password', [AsistantController::class, 'password'])->middleware('asistant')->name('asistant.password');
    Route::post('/profile/update-password', [AsistantController::class, 'passwordEdit'])->middleware('asistant')->name('asistant.password.submit');
    Route::get('/profile/edit/image', [AsistantController::class, 'image'])->middleware('asistant')->name('asistant.profile.image');
    Route::post('/profile/edit/image', [AsistantController::class, 'imageSubmit'])->middleware('asistant')->name('asistant.profile.image.submit');
    Route::get('/news-category', [AsistantNewsCategoryController::class, 'index'])->name('asistant.news-category')->middleware('asistant');
    Route::get('/news-category/add', [AsistantNewsCategoryController::class, 'create'])->name('asistant.news-category.add')->middleware('asistant');
    Route::post('/news-category/store', [AsistantNewsCategoryController::class, 'store'])->name('asistant.news-category.store')->middleware('asistant');
    Route::get('/news-category/edit/{id}', [AsistantNewsCategoryController::class, 'edit'])->name('asistant.news-category.edit')->middleware('asistant');
    Route::post('/news-category/update/{id}', [AsistantNewsCategoryController::class, 'update'])->name('asistant.news-category.update')->middleware('asistant');
    Route::get('/news-category/delete/{id}', [AsistantNewsCategoryController::class, 'destroy'])->name('asistant.news-category.delete')->middleware('asistant');
    Route::get('/news', [AsistantNewsController::class, 'index'])->name('asistant.news')->middleware('asistant');
    Route::get('/news/add', [AsistantNewsController::class, 'create'])->name('asistant.news.add')->middleware('asistant');
    Route::post('/news/store', [AsistantNewsController::class, 'store'])->name('asistant.news.store')->middleware('asistant');
    Route::get('/news/edit/{id}', [AsistantNewsController::class, 'edit'])->name('asistant.news.edit')->middleware('asistant');
    Route::post('/news/update/{id}', [AsistantNewsController::class, 'update'])->name('asistant.news.update')->middleware('asistant');
    Route::get('/news/detail/{id}', [AsistantNewsController::class, 'show'])->name('asistant.news.show')->middleware('asistant');
    Route::get('/news/delete/{id}', [AsistantNewsController::class, 'destroy'])->name('asistant.news.delete')->middleware('asistant');
    Route::get('/training-category', [AsistantTrainingCategoryController::class, 'index'])->name('asistant.training-category')->middleware('asistant');
    Route::get('/training-category/add', [AsistantTrainingCategoryController::class, 'create'])->name('asistant.training-category.add')->middleware('asistant');
    Route::post('/training-category/store', [AsistantTrainingCategoryController::class, 'store'])->name('asistant.training-category.store')->middleware('asistant');
    Route::get('/training-category/edit/{id}', [AsistantTrainingCategoryController::class, 'edit'])->name('asistant.training-category.edit')->middleware('asistant');
    Route::post('/training-category/update/{id}', [AsistantTrainingCategoryController::class, 'update'])->name('asistant.training-category.update')->middleware('asistant');
    Route::get('/training-category/delete/{id}', [AsistantTrainingCategoryController::class, 'destroy'])->name('asistant.training-category.delete')->middleware('asistant');
    Route::get('/training', [AsistantTrainingController::class, 'index'])->name('asistant.training')->middleware('asistant');
    Route::get('/training/add', [AsistantTrainingController::class, 'create'])->name('asistant.training.add')->middleware('asistant');
    Route::post('/training/store', [AsistantTrainingController::class, 'store'])->name('asistant.training.store')->middleware('asistant');
    Route::get('/training/edit/{id}', [AsistantTrainingController::class, 'edit'])->name('asistant.training.edit')->middleware('asistant');
    Route::post('/training/update/image/{id}', [AsistantTrainingController::class, 'updateImage'])->name('asistant.training.update.image')->middleware('asistant');
    Route::post('/training/update/form/{id}', [AsistantTrainingController::class, 'updateForm'])->name('asistant.training.update.form')->middleware('asistant');
    Route::post('/training/update/image-trainer/{id}', [AsistantTrainingController::class, 'updateImageTrainer'])->name('asistant.training.update.image.trainer')->middleware('asistant');
    Route::post('/training/update/form-trainer/{id}', [AsistantTrainingController::class, 'updateFormTrainer'])->name('asistant.training.update.form.trainer')->middleware('asistant');
    Route::get('/training/detail/{id}', [AsistantTrainingController::class, 'show'])->name('asistant.training.show')->middleware('asistant');
    Route::get('/training/delete/{id}', [AsistantTrainingController::class, 'destroy'])->name('asistant.training.delete')->middleware('asistant');
    Route::get('/training/learning-material/{id}', [AsistantTrainingController::class, 'learningMaterial'])->name('asistant.training.learning.material')->middleware('asistant');    
    Route::post('/training/learning-material/{id}', [AsistantTrainingController::class, 'uploadLearningMaterial'])->name('asistant.training.learning.material.upload')->middleware('asistant');    
    Route::get('/training/participants/{id}', [AsistantTrainingController::class, 'participants'])->name('asistant.training.participants')->middleware('asistant');
    Route::get('/training/participants/export/{id}', [AsistantTrainingController::class, 'export'])->name('asistant.training.participants.export')->middleware('asistant');
    Route::get('/training/status/active', [AsistantTrainingController::class, 'active'])->name('asistant.training.status.active')->middleware('asistant');
    Route::get('/training/status/unactive', [AsistantTrainingController::class, 'unactive'])->name('asistant.training.status.unactive')->middleware('asistant');
    Route::get('/release-category', [AsistantReleaseCategoryController::class, 'index'])->name('asistant.release-category')->middleware('asistant');
    Route::get('/release-category/add', [AsistantReleaseCategoryController::class, 'create'])->name('asistant.release-category.add')->middleware('asistant');
    Route::post('/release-category/store', [AsistantReleaseCategoryController::class, 'store'])->name('asistant.release-category.store')->middleware('asistant');
    Route::get('/release-category/edit/{id}', [AsistantReleaseCategoryController::class, 'edit'])->name('asistant.release-category.edit')->middleware('asistant');
    Route::post('/release-category/update/{id}', [AsistantReleaseCategoryController::class, 'update'])->name('asistant.release-category.update')->middleware('asistant');
    Route::get('/release-category/delete/{id}', [AsistantReleaseCategoryController::class, 'destroy'])->name('asistant.release-category.delete')->middleware('asistant');
    Route::get('/release', [AsistantReleaseController::class, 'index'])->name('asistant.release')->middleware('asistant');
    Route::get('/release/add', [AsistantReleaseController::class, 'create'])->name('asistant.release.add')->middleware('asistant');
    Route::post('/release/store', [AsistantReleaseController::class, 'store'])->name('asistant.release.store')->middleware('asistant');
    Route::get('/release/edit/{id}', [AsistantReleaseController::class, 'edit'])->name('asistant.release.edit')->middleware('asistant');
    Route::post('/release/update/{id}', [AsistantReleaseController::class, 'update'])->name('asistant.release.update')->middleware('asistant');
    Route::get('/release/detail/{id}', [AsistantReleaseController::class, 'show'])->name('asistant.release.show')->middleware('asistant');
    Route::get('/release/delete/{id}', [AsistantReleaseController::class, 'destroy'])->name('asistant.release.delete')->middleware('asistant');
    Route::get('/mahasiswa', [AsistantMahasiswaController::class, 'index'])->name('asistant.mahasiswa')->middleware('asistant');
    Route::get('/mahasiswa/add', [AsistantMahasiswaController::class, 'create'])->name('asistant.mahasiswa.add')->middleware('asistant');
    Route::post('/mahasiswa/store', [AsistantMahasiswaController::class, 'store'])->name('asistant.mahasiswa.store')->middleware('asistant');
    Route::get('/mahasiswa/edit/{id}', [AsistantMahasiswaController::class, 'edit'])->name('asistant.mahasiswa.edit')->middleware('asistant');
    Route::post('/mahasiswa/update/{id}', [AsistantMahasiswaController::class, 'update'])->name('asistant.mahasiswa.update')->middleware('asistant');
    Route::get('/mahasiswa/delete/{id}', [AsistantMahasiswaController::class, 'destroy'])->name('asistant.mahasiswa.delete')->middleware('asistant');
    Route::get('/dosen', [AsistantTeacherController::class, 'index'])->name('asistant.dosen')->middleware('asistant');
    Route::get('/dosen/add', [AsistantTeacherController::class, 'create'])->name('asistant.dosen.add')->middleware('asistant');
    Route::post('/dosen/store', [AsistantTeacherController::class, 'store'])->name('asistant.dosen.store')->middleware('asistant');
    Route::get('/dosen/edit/{id}', [AsistantTeacherController::class, 'edit'])->name('asistant.dosen.edit')->middleware('asistant');
    Route::post('/dosen/update/{id}', [AsistantTeacherController::class, 'update'])->name('asistant.dosen.update')->middleware('asistant');
    Route::get('/dosen/delete/{id}', [AsistantTeacherController::class, 'destroy'])->name('asistant.dosen.delete')->middleware('asistant');
    Route::get('/customer', [AsistantCustomerController::class, 'index'])->name('asistant.customer')->middleware('asistant');
    Route::get('/peralatan-lab', [AsistantToolController::class, 'index'])->name('asistant.tools')->middleware('asistant');
    Route::get('/peralatan-lab/add', [AsistantToolController::class, 'create'])->name('asistant.tool.create')->middleware('asistant');
    Route::post('/peralatan-lab/store', [AsistantToolController::class, 'store'])->name('asistant.tool.store')->middleware('asistant');
    Route::get('/peralatan-lab/edit/{id}', [AsistantToolController::class, 'edit'])->name('asistant.tool.edit')->middleware('asistant');
    Route::post('/peralatan-lab/update/{id}', [AsistantToolController::class, 'update'])->name('asistant.tool.update')->middleware('asistant');
    Route::get('/peralatan-lab/delete/{id}', [AsistantToolController::class, 'destroy'])->name('asistant.tool.delete')->middleware('asistant');
    Route::get('/peralatan-lab/export', [AsistantToolController::class, 'export'])->name('asistant.tool.export')->middleware('asistant');
    Route::get('/galeri', [AsistantGalleryController::class, 'index'])->name('asistant.galleries')->middleware('asistant');
    Route::get('/galeri/add', [AsistantGalleryController::class, 'create'])->name('asistant.gallery.add')->middleware('asistant');
    Route::post('/galeri/store', [AsistantGalleryController::class, 'store'])->name('asistant.gallery.store')->middleware('asistant');
    Route::get('/galeri/edit/{id}', [AsistantGalleryController::class, 'edit'])->name('asistant.gallery.edit')->middleware('asistant');
    Route::post('/galeri/update/{id}', [AsistantGalleryController::class, 'update'])->name('asistant.gallery.update')->middleware('asistant');
    Route::get('/galeri/edit-image/{id}', [AsistantGalleryController::class, 'editImage'])->name('asistant.gallery.edit.image')->middleware('asistant');
    Route::post('/galeri/update-image/{id}', [AsistantGalleryController::class, 'updateImage'])->name('asitant.gallery.update.image')->middleware('asitant');
    Route::get('/galeri/delete-image/{id}', [AsistantGalleryController::class, 'deleteImage'])->name('asistant.gallery.delete.image')->middleware('asistant');
    Route::get('/galeri/delete/{id}', [AsistantGalleryController::class, 'destroy'])->name('asistant.gallery.delete')->middleware('asistant');
    Route::get('/login', [AsistantController::class, 'index'])->name('asistant.login.form');
    Route::post('/login', [AsistantController::class, 'login'])->name('asistant.login');
    Route::get('/dashboard', [AsistantController::class, 'dashboard'])->name('asistant.dashboard')->middleware('asistant');
    Route::get('logout', [AsistantController::class, 'logout'])->name('asistant.logout')->middleware('asistant');
});

Route::prefix('dosen')->group(function(){
    Route::post('/berita/komentar/{id}', [DosenController::class, 'comment'])->middleware('dosen')->name('dosen.comment');
    Route::post('/rilis/komentar/{id}', [DosenController::class, 'commentRelease'])->middleware('dosen')->name('dosen.comment.release');
    Route::get('pengabdian-masyarakat', [CommunityDedicationController::class, 'index'])->middleware('dosen')->name('dosen.community.dedication');
    Route::get('/pengabdian-masyarakat/add', [CommunityDedicationController::class, 'create'])->name('dosen.community.dedication.add')->middleware('dosen');
    Route::post('/pengabdian-masyarakat/store', [CommunityDedicationController::class, 'store'])->name('dosen.community.dedication.store')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/edit/{id}', [CommunityDedicationController::class, 'edit'])->name('dosen.community.dedication.edit')->middleware('dosen');
    Route::post('/pengabdian-masyarakat/update/form/{id}', [CommunityDedicationController::class, 'update'])->name('dosen.community.dedication.update')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/detail/{id}', [CommunityDedicationController::class, 'show'])->name('dosen.community.dedication.show')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/delete/{id}', [CommunityDedicationController::class, 'destroy'])->name('dosen.community.dedication.delete')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/panduan/{id}', [CommunityDedicationController::class, 'guide'])->name('dosen.community.dedication.guide')->middleware('dosen');    
    Route::post('/pengabdian-masyarakat/panduan/{id}', [CommunityDedicationController::class, 'uploadGuide'])->name('dosen.community.dedication.upload.guide')->middleware('dosen');    
    Route::get('/pengabdian-masyarakat/participants/{id}', [CommunityDedicationController::class, 'participants'])->name('dosen.community.dedication.participants')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/participants-add/{id}', [CommunityDedicationController::class, 'participantsAdd'])->name('dosen.community.dedication.participants.add')->middleware('dosen');
    Route::post('/pengabdian-masyarakat/participants-store/{id}', [CommunityDedicationController::class, 'participantsStore'])->name('dosen.community.dedication.participants.store')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/participants-delete/{id}', [CommunityDedicationController::class, 'participantsDestroy'])->name('dosen.community.dedication.participants.delete')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/participants-user-detail/{id}', [CommunityDedicationController::class, 'participantsDetailUser'])->name('dosen.community.dedication.participants.user.detail')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/participants-dosen-detail/{id}', [CommunityDedicationController::class, 'participantsDetailDosen'])->name('dosen.community.dedication.participants.dosen.detail')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/participants/export/{id}', [CommunityDedicationController::class, 'export'])->name('dosen.community.dedication.participants.export')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/lain', [CommunityDedicationController::class, 'joins'])->name('dosen.community.dedication.joins')->middleware('dosen');
    Route::get('/pengabdian-masyarakat/lain/{id}', [CommunityDedicationController::class, 'join'])->name('dosen.community.dedication.join')->middleware('dosen');
    Route::get('penelitian', [ResearchTeacherController::class, 'index'])->name('dosen.penelitian')->middleware('dosen');
    Route::get('/penelitian/add', [ResearchTeacherController::class, 'create'])->name('dosen.penelitian.add')->middleware('dosen');
    Route::post('/penelitian/store', [ResearchTeacherController::class, 'store'])->name('dosen.penelitian.store')->middleware('dosen');
    Route::get('/penelitian/edit/{id}', [ResearchTeacherController::class, 'edit'])->name('dosen.penelitian.edit')->middleware('dosen');
    Route::post('/penelitian/update/form/{id}', [ResearchTeacherController::class, 'update'])->name('dosen.penelitian.update')->middleware('dosen');
    Route::get('/penelitian/detail/{id}', [ResearchTeacherController::class, 'show'])->name('dosen.penelitian.show')->middleware('dosen');
    Route::get('/penelitian/delete/{id}', [ResearchTeacherController::class, 'destroy'])->name('dosen.penelitian.delete')->middleware('dosen');
    Route::get('/penelitian/panduan/{id}', [ResearchTeacherController::class, 'guide'])->name('dosen.penelitian.guide')->middleware('dosen');    
    Route::post('/penelitian/panduan/{id}', [ResearchTeacherController::class, 'uploadGuide'])->name('dosen.penelitian.upload.guide')->middleware('dosen');    
    Route::get('/penelitian/participants/{id}', [ResearchTeacherController::class, 'participants'])->name('dosen.penelitian.participants')->middleware('dosen');
    Route::get('/penelitian/participants-add/{id}', [ResearchTeacherController::class, 'participantsAdd'])->name('dosen.penelitian.participants.add')->middleware('dosen');
    Route::post('/penelitian/participants-store/{id}', [ResearchTeacherController::class, 'participantsStore'])->name('dosen.penelitian.participants.store')->middleware('dosen');
    Route::get('/penelitian/participants-delete/{id}', [ResearchTeacherController::class, 'participantsDestroy'])->name('dosen.penelitian.participants.delete')->middleware('dosen');
    Route::get('/penelitian/participants-user-detail/{id}', [ResearchTeacherController::class, 'participantsDetailUser'])->name('dosen.penelitian.participants.user.detail')->middleware('dosen');
    Route::get('/penelitian/participants-dosen-detail/{id}', [ResearchTeacherController::class, 'participantsDetailDosen'])->name('dosen.penelitian.participants.dosen.detail')->middleware('dosen');
    Route::get('/penelitian/participants/export/{id}', [ResearchTeacherController::class, 'export'])->name('dosen.penelitian.participants.export')->middleware('dosen');
    Route::get('/penelitian/result/{id}', [ResearchTeacherController::class, 'result'])->name('dosen.penelitian.hasil');
    Route::post('/penelitian/result/{id}', [ResearchTeacherController::class, 'resultSubmit'])->name('dosen.penelitian.hasil.submit');
    Route::get('/penelitian/lain', [ResearchTeacherController::class, 'joins'])->name('dosen.penelitian.joins')->middleware('dosen');
    Route::get('/penelitian/lain/{id}', [ResearchTeacherController::class, 'join'])->name('dosen.penelitian.join')->middleware('dosen');
    Route::get('/berita', [DosenNewsController::class, 'index'])->name('dosen.berita');
    Route::get('/berita/add', [DosenNewsController::class, 'create'])->name('dosen.berita.add');
    Route::post('/berita/store', [DosenNewsController::class, 'store'])->name('dosen.berita.store');
    Route::get('/berita/edit/{id}', [DosenNewsController::class, 'edit'])->name('dosen.berita.edit');
    Route::post('/berita/update/{id}', [DosenNewsController::class, 'update'])->name('dosen.berita.update');
    Route::get('/berita/detail/{id}', [DosenNewsController::class, 'show'])->name('dosen.berita.show');
    Route::get('/berita/delete/{id}', [DosenNewsController::class, 'destroy'])->name('dosen.berita.delete');
    Route::get('/profile/edit', [DosenController::class, 'profile'])->middleware('dosen')->name('dosen.profile');
    Route::post('/profile/update', [DosenController::class, 'profileEdit'])->middleware('dosen')->name('dosen.profile.submit');
    Route::get('/profile/edit-password', [DosenController::class, 'password'])->middleware('dosen')->name('dosen.password');
    Route::post('/profile/update-password', [DosenController::class, 'passwordEdit'])->middleware('dosen')->name('dosen.password.submit');
    Route::get('/profile/edit/image', [DosenController::class, 'image'])->middleware('dosen')->name('dosen.profile.image');
    Route::post('/profile/edit/image', [DosenController::class, 'imageSubmit'])->middleware('dosen')->name('dosen.profile.image.submit');
    Route::get('/register', [DosenController::class, 'register'])->name('dosen.register');
    Route::post('/register', [DosenController::class, 'registerStore'])->name('dosen.register.store');
    Route::get('/login', [DosenController::class, 'index'])->name('dosen.login.form');
    Route::post('/login', [DosenController::class, 'login'])->name('dosen.login');
    Route::get('/dashboard', [DosenController::class, 'dashboard'])->name('dosen.dashboard')->middleware('dosen');
    Route::get('logout', [DosenController::class, 'logout'])->name('dosen.logout')->middleware('dosen');
});

Route::prefix('lead')->group(function(){
    Route::get('/profile/vission', [LeadProfileController::class, 'vission'])->middleware('lead')->name('lead.vission');
    Route::post('/profile/vission', [LeadProfileController::class, 'vissionUpdate'])->middleware('lead')->name('lead.vission.update');
    Route::get('/profile/mission', [LeadProfileController::class, 'mission'])->middleware('lead')->name('lead.mission');
    Route::post('/profile/mission', [LeadProfileController::class, 'missionUpdate'])->middleware('lead')->name('lead.mission.update');
    Route::get('/profile/goal', [LeadProfileController::class, 'goal'])->middleware('lead')->name('lead.goal');
    Route::post('/profile/goal', [LeadProfileController::class, 'goalUpdate'])->middleware('lead')->name('lead.goal.update');
    Route::get('/contact', [LeadContactController::class, 'index'])->middleware('lead')->name('lead.contact');
    Route::post('/contact', [LeadContactController::class, 'update'])->middleware('lead')->name('lead.contact.update');
    Route::get('/get-regency/ajax/{province_id}', [LeadContactController::class, 'GetRegency'])->middleware('lead');
    Route::get('/get-district/ajax/{regency_id}', [LeadContactController::class, 'GetDisctrict'])->middleware('lead');
    Route::get('/get-village/ajax/{district_id}', [LeadContactController::class, 'GetVillage'])->middleware('lead');
    Route::post('/berita/komentar/{id}', [LeadController::class, 'comment'])->middleware('lead')->name('lead.comment');
    Route::post('/rilis/komentar/{id}', [LeadController::class, 'commentRelease'])->middleware('lead')->name('lead.comment.release');
    Route::get('/profile/edit', [LeadController::class, 'profile'])->middleware('lead')->name('lead.profile');
    Route::post('/profile/update', [LeadController::class, 'profileEdit'])->middleware('lead')->name('lead.profile.submit');
    Route::get('/profile/edit-password', [LeadController::class, 'password'])->middleware('lead')->name('lead.password');
    Route::post('/profile/update-password', [LeadController::class, 'passwordEdit'])->middleware('lead')->name('lead.password.submit');
    Route::get('/profile/edit/image', [LeadController::class, 'image'])->middleware('lead')->name('lead.profile.image');
    Route::post('/profile/edit/image', [LeadController::class, 'imageSubmit'])->middleware('lead')->name('lead.profile.image.submit');
    Route::get('/news-category', [LeadNewsCategoryController::class, 'index'])->name('lead.news-category')->middleware('lead');
    Route::get('/news-category/add', [LeadNewsCategoryController::class, 'create'])->name('lead.news-category.add')->middleware('lead');
    Route::post('/news-category/store', [LeadNewsCategoryController::class, 'store'])->name('lead.news-category.store')->middleware('lead');
    Route::get('/news-category/edit/{id}', [LeadNewsCategoryController::class, 'edit'])->name('lead.news-category.edit')->middleware('lead');
    Route::post('/news-category/update/{id}', [LeadNewsCategoryController::class, 'update'])->name('lead.news-category.update')->middleware('lead');
    Route::get('/news-category/delete/{id}', [LeadNewsCategoryController::class, 'destroy'])->name('lead.news-category.delete')->middleware('lead');
    Route::get('/news', [LeadNewsController::class, 'index'])->name('lead.news')->middleware('lead');
    Route::get('/news/add', [LeadNewsController::class, 'create'])->name('lead.news.add')->middleware('lead');
    Route::post('/news/store', [LeadNewsController::class, 'store'])->name('lead.news.store')->middleware('lead');
    Route::get('/news/edit/{id}', [LeadNewsController::class, 'edit'])->name('lead.news.edit')->middleware('lead');
    Route::post('/news/update/{id}', [LeadNewsController::class, 'update'])->name('lead.news.update')->middleware('lead');
    Route::get('/news/detail/{id}', [LeadNewsController::class, 'show'])->name('lead.news.show')->middleware('lead');
    Route::get('/news/delete/{id}', [LeadNewsController::class, 'destroy'])->name('lead.news.delete')->middleware('lead');
    Route::get('/training-category', [LeadTrainingCategoryController::class, 'index'])->name('lead.training-category')->middleware('lead');
    Route::get('/training-category/add', [LeadTrainingCategoryController::class, 'create'])->name('lead.training-category.add')->middleware('lead');
    Route::post('/training-category/store', [LeadTrainingCategoryController::class, 'store'])->name('lead.training-category.store')->middleware('lead');
    Route::get('/training-category/edit/{id}', [LeadTrainingCategoryController::class, 'edit'])->name('lead.training-category.edit')->middleware('lead');
    Route::post('/training-category/update/{id}', [LeadTrainingCategoryController::class, 'update'])->name('lead.training-category.update')->middleware('lead');
    Route::get('/training-category/delete/{id}', [LeadTrainingCategoryController::class, 'destroy'])->name('lead.training-category.delete')->middleware('lead');
    Route::get('/training', [LeadTrainingController::class, 'index'])->name('lead.training')->middleware('lead');
    Route::get('/training/add', [LeadTrainingController::class, 'create'])->name('lead.training.add')->middleware('lead');
    Route::post('/training/store', [LeadTrainingController::class, 'store'])->name('lead.training.store')->middleware('lead');
    Route::get('/training/edit/{id}', [LeadTrainingController::class, 'edit'])->name('lead.training.edit')->middleware('lead');
    Route::post('/training/update/image/{id}', [LeadTrainingController::class, 'updateImage'])->name('lead.training.update.image')->middleware('lead');
    Route::post('/training/update/form/{id}', [LeadTrainingController::class, 'updateForm'])->name('lead.training.update.form')->middleware('lead');
    Route::post('/training/update/image-trainer/{id}', [LeadTrainingController::class, 'updateImageTrainer'])->name('lead.training.update.image.trainer')->middleware('lead');
    Route::post('/training/update/form-trainer/{id}', [LeadTrainingController::class, 'updateFormTrainer'])->name('lead.training.update.form.trainer')->middleware('lead');
    Route::get('/training/detail/{id}', [LeadTrainingController::class, 'show'])->name('lead.training.show')->middleware('lead');
    Route::get('/training/delete/{id}', [LeadTrainingController::class, 'destroy'])->name('lead.training.delete')->middleware('lead');
    Route::get('/training/learning-material/{id}', [LeadTrainingController::class, 'learningMaterial'])->name('lead.training.learning.material')->middleware('lead');    
    Route::post('/training/learning-material/{id}', [LeadTrainingController::class, 'uploadLearningMaterial'])->name('lead.training.learning.material.upload')->middleware('lead');    
    Route::get('/training/participants/{id}', [LeadTrainingController::class, 'participants'])->name('lead.training.participants')->middleware('lead');
    Route::get('/training/participants/export/{id}', [LeadTrainingController::class, 'export'])->name('lead.training.participants.export')->middleware('lead');
    Route::get('/training/status/active', [LeadTrainingController::class, 'active'])->name('lead.training.status.active')->middleware('lead');
    Route::get('/training/status/unactive', [LeadTrainingController::class, 'unactive'])->name('lead.training.status.unactive')->middleware('lead');
    Route::get('penelitian/mahasiswa', [LeadResearchController::class, 'student'])->name('lead.research.student')->middleware('lead');
    Route::get('penelitian/dosen', [LeadResearchController::class, 'teacher'])->name('lead.research.teacher')->middleware('lead');
    Route::get('penelitian/mahasiswa/detail/{id}', [LeadResearchController::class, 'show'])->name('lead.research.student.detail')->middleware('lead');
    Route::get('penelitian/dosen/detail/{id}', [LeadResearchController::class, 'show'])->name('lead.research.teacher.detail')->middleware('lead');
    Route::get('praktikum-mahasiswa', [LeadController::class, 'practice'])->name('lead.practice')->middleware('lead');
    Route::get('/release-category', [LeadReleaseCategoryController::class, 'index'])->name('lead.release-category')->middleware('lead');
    Route::get('/release-category/add', [LeadReleaseCategoryController::class, 'create'])->name('lead.release-category.add')->middleware('lead');
    Route::post('/release-category/store', [LeadReleaseCategoryController::class, 'store'])->name('lead.release-category.store')->middleware('lead');
    Route::get('/release-category/edit/{id}', [LeadReleaseCategoryController::class, 'edit'])->name('lead.release-category.edit')->middleware('lead');
    Route::post('/release-category/update/{id}', [LeadReleaseCategoryController::class, 'update'])->name('lead.release-category.update')->middleware('lead');
    Route::get('/release-category/delete/{id}', [LeadReleaseCategoryController::class, 'destroy'])->name('lead.release-category.delete')->middleware('lead');
    Route::get('/release', [LeadReleaseController::class, 'index'])->name('lead.release')->middleware('lead');
    Route::get('/release/add', [LeadReleaseController::class, 'create'])->name('lead.release.add')->middleware('lead');
    Route::post('/release/store', [LeadReleaseController::class, 'store'])->name('lead.release.store')->middleware('lead');
    Route::get('/release/edit/{id}', [LeadReleaseController::class, 'edit'])->name('lead.release.edit')->middleware('lead');
    Route::post('/release/update/{id}', [LeadReleaseController::class, 'update'])->name('lead.release.update')->middleware('lead');
    Route::get('/release/detail/{id}', [LeadReleaseController::class, 'show'])->name('lead.release.show')->middleware('lead');
    Route::get('/release/delete/{id}', [LeadReleaseController::class, 'destroy'])->name('lead.release.delete')->middleware('lead');
    Route::get('/mahasiswa', [LeadMahasiswaController::class, 'index'])->name('lead.mahasiswa')->middleware('lead');
    Route::get('/mahasiswa/add', [LeadMahasiswaController::class, 'create'])->name('lead.mahasiswa.add')->middleware('lead');
    Route::post('/mahasiswa/store', [LeadMahasiswaController::class, 'store'])->name('lead.mahasiswa.store')->middleware('lead');
    Route::get('/mahasiswa/edit/{id}', [LeadMahasiswaController::class, 'edit'])->name('lead.mahasiswa.edit')->middleware('lead');
    Route::post('/mahasiswa/update/{id}', [LeadMahasiswaController::class, 'update'])->name('lead.mahasiswa.update')->middleware('lead');
    Route::get('/mahasiswa/delete/{id}', [LeadMahasiswaController::class, 'destroy'])->name('lead.mahasiswa.delete')->middleware('lead');
    Route::get('/dosen', [LeadTeacherController::class, 'index'])->name('lead.dosen')->middleware('lead');
    Route::get('/dosen/add', [LeadTeacherController::class, 'create'])->name('lead.dosen.add')->middleware('lead');
    Route::post('/dosen/store', [LeadTeacherController::class, 'store'])->name('lead.dosen.store')->middleware('lead');
    Route::get('/dosen/edit/{id}', [LeadTeacherController::class, 'edit'])->name('lead.dosen.edit')->middleware('lead');
    Route::post('/dosen/update/{id}', [LeadTeacherController::class, 'update'])->name('lead.dosen.update')->middleware('lead');
    Route::get('/dosen/delete/{id}', [LeadTeacherController::class, 'destroy'])->name('lead.dosen.delete')->middleware('lead');
    Route::get('/galeri', [LeadGalleryController::class, 'index'])->name('lead.galleries')->middleware('lead');
    Route::get('/galeri/add', [LeadGalleryController::class, 'create'])->name('lead.gallery.add')->middleware('lead');
    Route::post('/galeri/store', [LeadGalleryController::class, 'store'])->name('lead.gallery.store')->middleware('lead');
    Route::get('/galeri/edit/{id}', [LeadGalleryController::class, 'edit'])->name('lead.gallery.edit')->middleware('lead');
    Route::post('/galeri/update/{id}', [LeadGalleryController::class, 'update'])->name('lead.gallery.update')->middleware('lead');
    Route::get('/galeri/edit-image/{id}', [LeadGalleryController::class, 'editImage'])->name('lead.gallery.edit.image')->middleware('lead');
    Route::post('/galeri/update-image/{id}', [LeadGalleryController::class, 'updateImage'])->name('lead.gallery.update.image')->middleware('lead');
    Route::get('/galeri/delete-image/{id}', [LeadGalleryController::class, 'deleteImage'])->name('lead.gallery.delete.image')->middleware('lead');
    Route::get('/galeri/delete/{id}', [LeadGalleryController::class, 'destroy'])->name('lead.gallery.delete')->middleware('lead');
    Route::get('/customer', [LeadCustomerController::class, 'index'])->name('lead.customer')->middleware('lead');
    Route::get('/login', [LeadController::class, 'index'])->name('lead.login.form');
    Route::post('/login', [LeadController::class, 'login'])->name('lead.login');
    Route::get('/dashboard', [LeadController::class, 'dashboard'])->name('lead.dashboard')->middleware('lead');
    Route::get('logout', [LeadController::class, 'logout'])->name('lead.logout')->middleware('lead');
});

Route::middleware('auth', 'verified')->group(function(){
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('mahasiswa/profile/edit', [DashboardController::class, 'profile'])->name('mahasiswa.profile');
    Route::post('mahasiswa/profile/update', [DashboardController::class, 'profileEdit'])->name('mahasiswa.profile.submit');
    Route::get('mahasiswa/profile/edit-password', [DashboardController::class, 'password'])->name('mahasiswa.password');
    Route::post('mahasiswa/profile/update-password', [DashboardController::class, 'passwordEdit'])->name('mahasiswa.password.submit');
    Route::get('mahasiswa/profile/edit/image', [DashboardController::class, 'image'])->name('mahasiswa.profile.image');
    Route::post('mahasiswa/profile/edit/image', [DashboardController::class, 'imageSubmit'])->name('mahasiswa.profile.image.submit');
    Route::post('mahasiswa/pelatihan/daftar/submit/{id}', [DashboardController::class, 'submit'])->name('mahasiswa.daftar.pelatihan.submit');
    Route::get('mahasiswa/pelatihan', [DashboardController::class, 'training'])->name('mahasiswa.pelatihan');
    Route::get('mahasiswa/pelatihan/{id}', [DashboardController::class, 'trainingDetail'])->name('mahasiswa.pelatihan.detail');
    Route::post('mahasiswa/pelatihan/absen', [DashboardController::class, 'absent'])->name('mahasiswa.pelatihan.absen');
    Route::get('mahasiswa/pengabdian-masyarakat/lain', [DashboardController::class, 'joins'])->name('mahasiswa.community.dedication.joins');
    Route::get('mahasiswa/pengabdian-masyarakat/lain/{id}', [DashboardController::class, 'join'])->name('mahasiswa.community.dedication.join');
    Route::post('mahasiswa/pengabdian-masyarakat/participants-store/{id}', [DashboardController::class, 'participantsStore'])->name('mahasiswa.community.dedication.participants.store');
    Route::post('mahasiswa/pengabdian-masyarakat/daftar/submit/{id}', [DashboardController::class, 'dedicationSubmit'])->name('mahasiswa.daftar.pengabdian.submit');
    Route::get('mahasiswa/penelitian', [ResearchController::class, 'list'])->name('mahasiswa.penelitian.individu');
    Route::get('mahasiswa/penelitian/hasil/{id}', [ResearchController::class, 'result'])->name('mahasiswa.penelitian.individu.hasil');
    Route::get('mahasiswa/penelitian/informasi/{id}', [ResearchController::class, 'information'])->name('mahasiswa.penelitian.individu.information');
    Route::post('mahasiswa/penelitian/hasil/{id}', [ResearchController::class, 'resultSubmit'])->name('mahasiswa.penelitian.individu.hasil.submit');
    Route::get('mahasiswa/penelitian/lain', [DashboardController::class, 'listResearchTeacher'])->name('mahasiswa.penelitian.joins'); 
    Route::get('mahasiswa/penelitian/lain/{id}', [DashboardController::class, 'researchTeacherDetail'])->name('mahasiswa.penelitian.join'); 
    Route::post('mahasiswa/penelitian/participants-store/{id}', [DashboardController::class, 'participantsResearchStore'])->name('mahasiswa.penelitian.participants.store');
    Route::post('mahasiswa/penelitian/daftar/submit/{id}', [DashboardController::class, 'researchSubmit'])->name('mahasiswa.daftar.penelitian.submit');
    Route::get('mahasiswa/praktikum', [DashboardController::class, 'lesson'])->name('mahasiswa.praktikum');
    Route::get('mahasiswa/berita', [UserNewsController::class, 'index'])->name('mahasiswa.berita');
    Route::get('mahasiswa/berita/add', [UserNewsController::class, 'create'])->name('mahasiswa.berita.add');
    Route::post('mahasiswa/berita/store', [UserNewsController::class, 'store'])->name('mahasiswa.berita.store');
    Route::get('mahasiswa/berita/edit/{id}', [UserNewsController::class, 'edit'])->name('mahasiswa.berita.edit');
    Route::post('mahasiswa/berita/update/{id}', [UserNewsController::class, 'update'])->name('mahasiswa.berita.update');
    Route::get('mahasiswa/berita/detail/{id}', [UserNewsController::class, 'show'])->name('mahasiswa.berita.show');
    Route::get('mahasiswa/berita/delete/{id}', [UserNewsController::class, 'destroy'])->name('mahasiswa.berita.delete');
    Route::get('mahasiswa/daftar/member', [DashboardController::class, 'member'])->name('mahasiswa.daftar.member');
    Route::post('mahasiswa/daftar/member/submit', [DashboardController::class, 'memberEnroll'])->name('mahasiswa.daftar.member.submit');
    Route::get('mahasiswa/message', [DashboardController::class, 'message'])->name('mahasiswa.message');
    Route::post('mahasiswa/message/reply/{id}', [DashboardController::class, 'reply'])->name('mahasiswa.message.reply.submit');
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium', [DashboardController::class, 'certificateClearenceLaboratoryView'])->name('mahasiswa.laboratory.clearance.certificate'); 
    Route::post('mahasiswa/surat-keterangan-bebas-laboratorium', [DashboardController::class, 'certificateClearenceLaboratorySubmit'])->name('mahasiswa.laboratory.clearance.certificate.submit'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-basis_data/{id}', [DashboardController::class, 'certificateClearenceLaboratoryBasisData'])->name('mahasiswa.laboratory.clearance.certificate.basis.data'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-multimedia/{id}', [DashboardController::class, 'certificateClearenceLaboratoryMultimedia'])->name('mahasiswa.laboratory.clearance.certificate.multimedia'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-robotika/{id}', [DashboardController::class, 'certificateClearenceLaboratoryRobotika'])->name('mahasiswa.laboratory.clearance.certificate.robotika'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-elektronika/{id}', [DashboardController::class, 'certificateClearenceLaboratoryElektronika'])->name('mahasiswa.laboratory.clearance.certificate.elektronika'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-perangkat_keras/{id}', [DashboardController::class, 'certificateClearenceLaboratoryPerangkatKeras'])->name('mahasiswa.laboratory.clearance.certificate.perangkat.keras'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-struktur_data/{id}', [DashboardController::class, 'certificateClearenceLaboratoryStrukturData'])->name('mahasiswa.laboratory.clearance.certificate.struktur.data'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-pemrograman_lanjut/{id}', [DashboardController::class, 'certificateClearenceLaboratoryPemrogramanLanjut'])->name('mahasiswa.laboratory.clearance.certificate.pemrograman.lanjut'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-instrumen/{id}', [DashboardController::class, 'certificateClearenceLaboratoryInstrumen'])->name('mahasiswa.laboratory.clearance.certificate.instrumen'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-kecerdasan/{id}', [DashboardController::class, 'certificateClearenceLaboratoryKecerdasan'])->name('mahasiswa.laboratory.clearance.certificate.kecerdasan'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-jaringan/{id}', [DashboardController::class, 'certificateClearenceLaboratoryJaringan'])->name('mahasiswa.laboratory.clearance.certificate.jaringan'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-pengolahan/{id}', [DashboardController::class, 'certificateClearenceLaboratoryPengolahan'])->name('mahasiswa.laboratory.clearance.certificate.pengolahan'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-rpl/{id}', [DashboardController::class, 'certificateClearenceLaboratoryRpl'])->name('mahasiswa.laboratory.clearance.certificate.rpl'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-pemrograman_dasar/{id}', [DashboardController::class, 'certificateClearenceLaboratoryPemrogramanDasar'])->name('mahasiswa.laboratory.clearance.certificate.pemrograman.dasar'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium-pemrograman_internet/{id}', [DashboardController::class, 'certificateClearenceLaboratoryPemrogramanInternet'])->name('mahasiswa.laboratory.clearance.certificate.pemrograman.internet'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium/kpm/{id}', [DashboardController::class, 'kpm'])->name('mahasiswa.laboratory.clearance.certificate.kpm'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium/laporan-kp/{id}', [DashboardController::class, 'laporanKp'])->name('mahasiswa.laboratory.clearance.certificate.laporan.kp'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium/form-ujian-ta/{id}', [DashboardController::class, 'formUjianTa'])->name('mahasiswa.laboratory.clearance.certificate.form.ujian.ta'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium/pengesahan-kp/{id}', [DashboardController::class, 'pengesahanKp'])->name('mahasiswa.laboratory.clearance.certificate.pengesahan.kp'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium/tanda-terima-proposal/{id}', [DashboardController::class, 'tandaTerimaProposal'])->name('mahasiswa.laboratory.clearance.certificate.tanda.terima.proposal'); 
    Route::get('mahasiswa/surat-keterangan-bebas-laboratorium/form-pengajuan/{id}', [DashboardController::class, 'formPengajuan'])->name('mahasiswa.laboratory.clearance.certificate.form.pengajuan'); 
    Route::get('mahasiswa/mahasiswa/logout', [DashboardController::class, 'logout'])->name('mahasiswa.logout');
});

require __DIR__.'/auth.php';
